-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 02:35:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classicmodels
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classicmodels
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classicmodels` DEFAULT CHARACTER SET latin1 ;
USE `classicmodels` ;

-- -----------------------------------------------------
-- Table `classicmodels`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`customers` (
  `customerNumber` INT NOT NULL,
  `customerName` VARCHAR(50) NOT NULL,
  `contactLastName` VARCHAR(50) NOT NULL,
  `contactFirstName` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `postalCode` VARCHAR(15) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `creditLimit` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`employees` (
  `employeeNumber` INT NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `jobTitle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`employeeNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`offices` (
  `officeCode` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `territory` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`orderdetails` (
  `quantityOrdered` INT NOT NULL,
  `priceEach` DECIMAL(10,2) NOT NULL,
  `orderLineNumber` SMALLINT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`orders` (
  `orderNumber` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`payments` (
  `checkNumber` VARCHAR(50) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`checkNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`productlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`productlines` (
  `productLine` VARCHAR(50) NOT NULL,
  `textDescription` VARCHAR(4000) NULL DEFAULT NULL,
  `htmlDescription` MEDIUMTEXT NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`products` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NOT NULL,
  `productScale` VARCHAR(10) NOT NULL,
  `productVendor` VARCHAR(50) NOT NULL,
  `productDescription` TEXT NOT NULL,
  `quantityInStock` SMALLINT NOT NULL,
  `buyPrice` DECIMAL(10,2) NOT NULL,
  `MSRP` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`productCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classicmodels`.`TH_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classicmodels`.`TH_Ventas` (
  `id_Transacciones` INT NOT NULL,
  `products_productCode` VARCHAR(15) NOT NULL,
  `productlines_productLine` VARCHAR(50) NOT NULL,
  `orders_orderNumber` INT NOT NULL,
  `offices_officeCode` VARCHAR(10) NOT NULL,
  `employees_employeeNumber` INT NOT NULL,
  `payments_checkNumber` VARCHAR(50) NOT NULL,
  `customers_customerNumber` INT NOT NULL,
  `cantidad_vendida` INT NULL,
  `cantidad_producto` INT NULL,
  PRIMARY KEY (`id_Transacciones`, `products_productCode`, `productlines_productLine`, `orders_orderNumber`, `offices_officeCode`, `employees_employeeNumber`, `payments_checkNumber`, `customers_customerNumber`),
  INDEX `fk_TH_Ventas_products1_idx` (`products_productCode` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_productlines1_idx` (`productlines_productLine` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_orders1_idx` (`orders_orderNumber` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_offices1_idx` (`offices_officeCode` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_employees1_idx` (`employees_employeeNumber` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_payments1_idx` (`payments_checkNumber` ASC) VISIBLE,
  INDEX `fk_TH_Ventas_customers1_idx` (`customers_customerNumber` ASC) VISIBLE,
  CONSTRAINT `fk_TH_Ventas_products1`
    FOREIGN KEY (`products_productCode`)
    REFERENCES `classicmodels`.`products` (`productCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_productlines1`
    FOREIGN KEY (`productlines_productLine`)
    REFERENCES `classicmodels`.`productlines` (`productLine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_orders1`
    FOREIGN KEY (`orders_orderNumber`)
    REFERENCES `classicmodels`.`orders` (`orderNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_offices1`
    FOREIGN KEY (`offices_officeCode`)
    REFERENCES `classicmodels`.`offices` (`officeCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_employees1`
    FOREIGN KEY (`employees_employeeNumber`)
    REFERENCES `classicmodels`.`employees` (`employeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_payments1`
    FOREIGN KEY (`payments_checkNumber`)
    REFERENCES `classicmodels`.`payments` (`checkNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TH_Ventas_customers1`
    FOREIGN KEY (`customers_customerNumber`)
    REFERENCES `classicmodels`.`customers` (`customerNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
